name: Build and Deploy Code

on: [push, pull_request]

jobs:
  first job:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name : Say Welcom to FASTAPI
        run : echo "Nice to do that"