name: Build and Deploy Code

on: [push, pull_request]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install Python v3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install all requirements
        run : pip install -r requirements.txt
